apiVersion: v1
kind: Service
metadata:
  name: keel-mailer
  namespace: "keel"
  labels:
    app: keel-mailer
spec:
  ports:
  - port: 80
    targetPort: 6000
    protocol: TCP
    name: keel-mailer
  selector:
    app: keel-mailer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel-mailer
  namespace: "keel"
  labels:
    app: keel-mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel-mailer
  template:
    metadata:
      labels:
        app: keel-mailer
    spec:
      containers:
      - name: keel-mailer
        image: ghcr.io/zozs/keel-mailer:latest
        imagePullPolicy: Always
        # These should preferably be set as secrets instead, but are listed here for completeness.
        env:
        - name: SMTP_HOST
          value: mail.example.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: user
        - name: SMTP_PASS
          value: pass
        - name: SMTP_SENDER
          value: keel@example.com
        - name: SMTP_RECIPIENT
          value: devops-team@example.com
        - name: KEEL_HOST
          value: http://keel.keel.svc.cluster.local:9300
        - name: KEEL_USER
          value: admin
        - name: KEEL_PASS
          value: admin
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
